version: '3.7'

services:
  frontend:
    build: 
      context: .
    container_name: frontend
    ports:
      - "1233:3000"
      - "1234:3002"
    volumes:
      - ./src:/app/src
    environment:
      - CHOKIDAR_USEPOLLING=true