version: '3.7'

services:
  frontend:
    build: 
      context: .
    container_name: frontend
    ports:
      - "3002:3002"
    volumes:
      - ./src:/app/src
    environment:
      - CHOKIDAR_USEPOLLING=true